# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0f770fe120c0cec603ca1500252e839a4b8c2f1b51dc644f3c8cfa346708db2361e88c8035a375a30df2f8f827b75959172f4e1e21e510b157cf32b78da5213

test:
  secret_key_base: aa6043fbe8957c6fbdd0908d6a2451569a81aa2bf9bfbd3beb22110ea31491a270232b77c6360d2f7b4ce74c1b52eb4a68aaa23944781e594fe049848af15944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
